/***********************************************************************************************
* Name              : xmlnsOracleComPcbpelAdapterDbTopC_Test                                                 
* Description       : Test class for xmlnsOracleComPcbpelAdapterDbTopC                                             
* Created Date      : 04/06/2018                                                    
* Created By        : Adeel Ahmad (adeel.ahmad@weare4c.com)    
* Jira/Req By       :                                                                                                                                         
* ----------------------------------------------------------------------------------------------
* VERSION   Developer   Date        Description     Ticket/Reference                                                                    
* 1.0       Adeel       04/06/2018  Created                              
************************************************************************************************/
@IsTest
public with sharing class xmlnsOracleComPcbpelAdapterDbTopC_Test {
    private static testMethod void coverFields(){
        new xmlnsOracleComPcbpelAdapterDbTopC.xxemrSecurityJointownerVCollection_element();
        new xmlnsOracleComPcbpelAdapterDbTopC.XxemrSecurityChkActionV();
        new xmlnsOracleComPcbpelAdapterDbTopC.XxemrSecurityJointownerV();
        new xmlnsOracleComPcbpelAdapterDbTopC.XxemrCustomerSecurityChkV();
        new xmlnsOracleComPcbpelAdapterDbTopC.CustomerSecurityCheckSelect_fromDate_toDate();
        new xmlnsOracleComPcbpelAdapterDbTopC.XxemrCustomerSecurityChkVCollection();
        new xmlnsOracleComPcbpelAdapterDbTopC.xxemrSecurityChkActionVCollection_element();
    }
}